### ISSUE TITLE
Code for Motion Retargeting

### ISSUE THREAD

**Issue by TongZhangTHU** [cvlab-columbia/drrobot#1]
Hi,

Thank you for your amazing work on this project! I am wondering if you have any plans to release the code for Motion Retargeting, or if it has already been included and I may have missed it?

**Comment by ruoshiliu** [comment]
Hi @TongZhangTHU , thank you for your interest in our project. Since we refactored our rendering codebase significantly to make it more efficient, our motion retargeting code will not be compatible with the current version. If you have any specific questions regarding implementation, I'm happy to answer them for you.

**Comment by TongZhangTHU** [comment]
Thank you for your response!
