### ISSUE TITLE
camera optimization accuracy

### ISSUE THREAD

**Issue by Yanbing-Han** [cvlab-columbia/drrobot#5]
I am playing the demo `gradio_app_reconstruct.py` with the robot ur5 you provided.
It seems quite challenging to recover the camera position after randomly initializing the target camera (joint fixed). 
Is this behavior expected ?

**Comment by ruoshiliu** [comment]
Hi @Han230104 , thank you for your interest in our project. Yes it's not always guaranteed to succeed especially when the camera pose and the robot pose are jointly optimized. The demo serves as a minimal demo to present our tool. In practice, we suggest you initialize multiple random seeds during optimization (and perhaps parallelize these seeds to speed up) and select the best reconstruction. This is a common practice and should still be relatively efficient due to the efficient rendering method.

**Comment by Yanbing-Han** [comment]
I see. I'll close this.
